// <auto-generated />
using HandBallLeague.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HandBallLeague.DataAccess.Migrations
{
    [DbContext(typeof(HandBallLeagueContext))]
    [Migration("20241019072439_ExtendedTableForEntities")]
    partial class ExtendedTableForEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HandBallLeague.DataAccess.Entities.CoachDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeOfCoach")
                        .HasColumnType("int");

                    b.Property<string>("NameOfCoach")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<float>("Salary")
                        .HasColumnType("real");

                    b.Property<string>("SurnameOfCoach")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TeamDBId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamDBId")
                        .IsUnique();

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("HandBallLeague.DataAccess.Entities.MatchDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Audience")
                        .HasColumnType("int");

                    b.Property<int>("GuestsScore")
                        .HasColumnType("int");

                    b.Property<string>("GuestsTeamId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HostsScore")
                        .HasColumnType("int");

                    b.Property<string>("HostsTeamId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("HandBallLeague.DataAccess.Entities.PlayerDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeOfPlayer")
                        .HasColumnType("int");

                    b.Property<string>("NameOfPlayer")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<float>("Salary")
                        .HasColumnType("real");

                    b.Property<string>("SurnameOfPlayer")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TeamDBId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamDBId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("HandBallLeague.DataAccess.Entities.TeamDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("BudgetOfTeam")
                        .HasColumnType("real");

                    b.Property<string>("CityOfTeam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("FoundingYear")
                        .HasColumnType("int");

                    b.Property<string>("NameOfTeam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("MatchDBTeamDB", b =>
                {
                    b.Property<int>("MatchesId")
                        .HasColumnType("int");

                    b.Property<int>("TeamsId")
                        .HasColumnType("int");

                    b.HasKey("MatchesId", "TeamsId");

                    b.HasIndex("TeamsId");

                    b.ToTable("MatchDBTeamDB");
                });

            modelBuilder.Entity("HandBallLeague.DataAccess.Entities.CoachDB", b =>
                {
                    b.HasOne("HandBallLeague.DataAccess.Entities.TeamDB", "TeamDB")
                        .WithOne("CoachDB")
                        .HasForeignKey("HandBallLeague.DataAccess.Entities.CoachDB", "TeamDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamDB");
                });

            modelBuilder.Entity("HandBallLeague.DataAccess.Entities.PlayerDB", b =>
                {
                    b.HasOne("HandBallLeague.DataAccess.Entities.TeamDB", "TeamDB")
                        .WithMany("Players")
                        .HasForeignKey("TeamDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamDB");
                });

            modelBuilder.Entity("MatchDBTeamDB", b =>
                {
                    b.HasOne("HandBallLeague.DataAccess.Entities.MatchDB", null)
                        .WithMany()
                        .HasForeignKey("MatchesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HandBallLeague.DataAccess.Entities.TeamDB", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HandBallLeague.DataAccess.Entities.TeamDB", b =>
                {
                    b.Navigation("CoachDB")
                        .IsRequired();

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
